### PR TITLE
Simplify anonymization of an article

### PR DESCRIPTION
**Pull request by csware**
Added a new documentclass option anonymous and new macro `\anon` fo simplifying anonymization. I saw this in the acmart and found this really useful.

The `\thanks` macro could be replaced with a placeholder... But this doesn't seem to be an issue ATM as thanks seems to be broken anyways.

### CODE REVIEW

**Comment by csware** [comment]
@sieversMartin I rebased this.

How to build lni.pdf?

**Comment by csware** [comment]
@koppor Updated.

**Review by koppor — APPROVED** [review]

**Comment by koppor** [comment]
CHANGELOG.md entry added at https://github.com/gi-ev/LNI/commit/6035f206e41b0ce611e330f89e8163424f3b36ab

**Comment by koppor** [comment]
Side note: No need to force-push. I am doing a squash-merge (creating one commit in the main branch) at the merge. - Having separate commits in the PR helps to review. In the concrete case, I spent five minutes searching for the `&` in the diff until I realized that there was a force push ^^.

**Comment by csware** [comment]
I prefer clean history.

**Pull request merged**
