### PR TITLE
Sync Bibliography and Literaturverzeichnis with Word template (also the style)

### PR DESCRIPTION
**Pull request by csware**
For some reason `\refname` (https://github.com/gi-ev/LNI/pull/103/files#diff-ae80ebe131a821ba5cd1a749bc40e873a09e9ae3719c48dec09032d1dc42da29L515) get overwritten and cannot be used.

### CODE REVIEW

**Comment by koppor** [comment]
I need some more time to port this to biblatex-lni, because I need to update the build process (https://github.com/gi-ev/biblatex-lni/issues/7), also switching from CircleCI to GitHub actions (as I did at https://github.com/gi-ev/LNI/pull/105).

**Comment by koppor** [comment]
@csware I ported the font size change at https://github.com/gi-ev/LNI/pull/114. I think, this should also go into biblatex-lni (as outlined at https://github.com/gi-ev/LNI/pull/114#issuecomment-1628422510). What's your take on this?

**Comment by koppor** [comment]
Heading ported at: https://github.com/gi-ev/biblatex-lni/pull/12

I am not sure about the font size comment in your PR. I assume (hope ^^) that the font size of the heading does not need to be adjusted.

In case there are not any blocking issues, I will release the next version of biblatex-lni the next days.

**Comment by csware** [comment]
Yes, the font size needs to be adjusted, but only for the German version

**Comment by koppor** [comment]
> For some reason `\refname` ([#103 (files)](https://github.com/gi-ev/LNI/pull/103/files#diff-ae80ebe131a821ba5cd1a749bc40e873a09e9ae3719c48dec09032d1dc42da29L515)) get overwritten and cannot be used.

Reason: bibtex (`\refname`) works different than biblatex (which uses its own dictionary)

Note that `biblliography` is dfferent from `references`. Fixed at https://github.com/gi-ev/biblatex-lni/pull/24

**Pull request closed without merging**
