### PR TITLE
[WIP] Initial full example document for German authors

### PR DESCRIPTION
**Pull request by koppor**
Based on the old template, I generated lni-paper-example.de.tex.

From my side, there are two things left:

- [x] investigate difference in rendering at verbatim and lstlisting
- [ ] include it in `lni.dtx`

<s>Here the different output of verbatim and lstlisting is shown. I like the output of verbatim more:

grafik
</s>

### CODE REVIEW

**Comment by sieversMartin** [comment]
Regarding the differences between `verbatim` and `listings`: the later is far more complex (in a positive sense) and can be configured in a wide way, e.g. to look like `verbatim`

**Comment by koppor** [comment]
I solved it by configuring lstlistings "correctly" (9edf856)

> the default setting of listings with "fixed columns" has a space 0.6em wide, while the characters in Computer Modern Typewriter are 0.5em wide. 

Source: https://tex.stackexchange.com/a/179072/9075

**Comment by koppor** [comment]
I updated the example to have one line per sentence so that is easier to view the diffs using git etc.

I tried to include it in the lni.dtx file. The issue is the magic line:

    % !TeX spellcheck = de_DE

When put as this into `lni.dtx`, it gets removed. If one puts it with two `%%`, then both are in the `lni-paper-example-de.tex` file:

    %% !TeX spellcheck = de_DE

This is not desired as `%%` are not common. Tooling should not dominate the users.

I discovered [makedtx](https://www.ctan.org/pkg/makedtx), but I think, it's not of help, is it?

**Comment by sieversMartin** [comment]
I finally found a way using a special form of preamble:
``` latex
\def\templatepre{%
\perCent\space !TeX encoding = UTF-8^^J%
\perCent\space !TeX program = pdflatex^^J%
\perCent\space !BIB program = bibtex^^J%
\perCent\space !TeX spellcheck = de_DE^^J%
}
```

See `lni.dtx` for more details.

**Comment by sieversMartin** [comment]
Integration completed IMHO

**Pull request merged**
