### PR TITLE
Fix hyperlinks to references

### PR DESCRIPTION
**Pull request by koppor**
Fixes https://github.com/gi-ev/LNI/issues/107

(and minor adaptions to build.sh and wording at lni.dtx)

### CODE REVIEW

**Comment by sieversMartin** [comment]
I am not sure, whether loading in the middle of the preamble is a good idea. We should look for another solution IMHO.

**Comment by sieversMartin** [comment]
We should keep the load order, but work with `hyperref=manual` and `\BiblatexManualHyperrefOn`. See https://github.com/gi-ev/LNI/tree/fix-107-ms

**Comment by koppor** [comment]
The fix looks nice! Thank you.

In general, we should think about supporting addition of packages, which need to be loaded after hyperref. A huge discussion is at https://tex.stackexchange.com/q/1863/9075. - I am very glad that no user reported issues in loading additional packages. I am unsure whether this is luck or because the class is properly engineered ^^.

Maybe using [`pkgloader`](https://github.com/mhelvens/latex-pkgloader) could help? However, this is a solution not widely in use and may cause other issues.

**Comment by koppor** [comment]
I close this PR and will merge the other commit to move forward.

**Pull request closed without merging**
